# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    # Run Java tests
    # https://docs.fastlane.tools/getting-started/android/running-tests/
    gradle(task: "test")
  end

  desc "Build the app"
  lane :build do
    # Build the app
    # https://docs.fastlane.tools/getting-started/android/beta-deployment/#building-your-app
    # It`s necessary to update the app to sign automaticaly
    # https://developer.android.com/studio/publish/app-signing#sign-auto
    gradle(task: "clean assembleRelease")
    # Moving the result bin to root
    sh 'mv $(find ../app/build -name *.apk) ../app.apk'
  end

  desc "Upload to Crashlytics"
  lane :fabric do
    crashlytics(apk_path:'app.apk')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
